In [3]:
import pandas as pd
import numpy as np

ModuleNotFoundError: No module named 'pandas'

In [ ]:
df = pd.read_csv("data/Cleaned_Data_Financial_Complaints.csv")

NameError: name 'pd' is not defined

In [ ]:
df.head(2)

,Complaint ID,Submitted via,Date submitted,Date received,State,State_Latitude,State_Longitude,Product,Sub-product,Issue,Sub-issue,Company public response,Company response to consumer,Timely response?,Census_Region,Census_Division,Company_Response_Date,Company_ID_1081,Response_Time_Days
0,4848023,Referral,44493,44496,NY,42.165726,-74.948051,Mortgage,Conventional home mortgage,Applying for a mortgage or refinancing an exis...,NaN,Company has responded to the consumer and the ...,Closed with explanation,Yes,Northeast,Middle Atlantic,44499,COMP-0820,6
1,3621464,Web,43945,43945,FL,27.766279,-81.686783,"Money transfer, virtual currency, or money ser...",Refund anticipation check,Lost or stolen check,NaN,Company has responded to the consumer and the ...,Closed with monetary relief,Yes,South,South Atlantic,43964,COMP-0115,19

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62516 entries, 0 to 62515
Data columns (total 19 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Complaint ID                  62516 non-null  int64
 1   Submitted via                 62516 non-null  object
 2   Date submitted                62516 non-null  int64
 3   Date received                 62516 non-null  int64
 4   State                         62516 non-null  object
 5   State_Latitude                62516 non-null  float64
 6   State_Longitude               62516 non-null  float64
 7   Product                       62516 non-null  object
 8   Sub-product                   62509 non-null  object
 9   Issue                         62516 non-null  object
 10  Sub-issue                     51658 non-null  object
 11  Company public response       60341 non-null  object
 12  Company response to consumer  62516 non-null  object
 13  Timely response?              61022 non-null  object
 14  Census_Region                 62516 non-null  object
 15  Census_Division               62516 non-null  object
 16  Company_Response_Date         62516 non-null  int64
 17  Company_ID_1081               62516 non-null  object
 18  Response_Time_Days            62516 non-null  int64
dtypes: float64(2), int64(5), object(12)
memory usage: 9.1+ MB

In [ ]:
df.describe()

,Complaint ID,Date submitted,Date received,State_Latitude,State_Longitude,Company_Response_Date,Response_Time_Days
count,6.251600e+04,62516.000000,62516.000000,62516.000000,62516.000000,62516.000000,62516.000000
mean,4.512642e+06,44159.671700,44160.896586,36.886985,-93.963607,44174.760173,15.088473
std,1.442917e+06,675.231304,675.085479,5.016981,18.467921,675.287997,8.913996
min,2.471340e+06,42856.000000,42856.000000,21.094318,-157.498337,42857.000000,0.000000
25%,3.254020e+06,43607.000000,43613.000000,33.729759,-119.681564,43622.000000,7.000000
50%,4.178582e+06,44257.000000,44258.000000,36.116203,-84.670067,44272.000000,15.000000
75%,5.771284e+06,44756.000000,44757.000000,40.349457,-78.169968,44771.000000,23.000000
max,7.458912e+06,45166.000000,45166.000000,61.370716,-69.381927,45190.000000,30.000000

In [ ]:
df.shape

(62516, 19)

In [ ]:
df['Complaint ID'].count().sum()

np.int64(62516)

In [ ]:
df.isnull().sum()

Complaint ID                        0
Submitted via                       0
Date submitted                      0
Date received                       0
State                               0
State_Latitude                      0
State_Longitude                     0
Product                             0
Sub-product                         7
Issue                               0
Sub-issue                       10858
Company public response          2175
Company response to consumer        0
Timely response?                 1494
Census_Region                       0
Census_Division                     0
Company_Response_Date               0
Company_ID_1081                     0
Response_Time_Days                  0
dtype: int64

In [ ]:
origin_date = pd.to_datetime('1899-12-30')
date_columns = ['Date submitted', 'Date received', 'Company_Response_Date']

for col in date_columns:
    df[col] = origin_date + pd.to_timedelta(df[col], unit='D')

In [ ]:
df.head()

,Complaint ID,Submitted via,Date submitted,Date received,State,State_Latitude,State_Longitude,Product,Sub-product,Issue,Sub-issue,Company public response,Company response to consumer,Timely response?,Census_Region,Census_Division,Company_Response_Date,Company_ID_1081,Response_Time_Days
0,4848023,Referral,2021-10-24,2021-10-27,NY,42.165726,-74.948051,Mortgage,Conventional home mortgage,Applying for a mortgage or refinancing an exis...,Not Specified,Company has responded to the consumer and the ...,Closed with explanation,Yes,Northeast,Middle Atlantic,2021-10-30,COMP-0820,6
1,3621464,Web,2020-04-24,2020-04-24,FL,27.766279,-81.686783,"Money transfer, virtual currency, or money ser...",Refund anticipation check,Lost or stolen check,Not Specified,Company has responded to the consumer and the ...,Closed with monetary relief,Yes,South,South Atlantic,2020-05-13,COMP-0115,19
2,5818349,Web,2022-07-27,2022-07-27,CA,36.116203,-119.681564,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Account information incorrect,Company has responded to the consumer and the ...,Closed with explanation,Yes,West,Pacific,2022-08-24,COMP-0408,28
3,7233015,Referral,2023-07-10,2023-07-11,CA,36.116203,-119.681564,Credit card or prepaid card,General-purpose prepaid card,Problem getting a card or closing an account,"Trouble getting, activating, or registering a ...",Not Specified,In progress,Not Specified,West,Pacific,2023-07-24,COMP-0045,14
4,5820224,Referral,2022-07-27,2022-07-28,VA,37.769337,-78.169968,Credit card or prepaid card,General-purpose credit card or charge card,Closing your account,Company closed your account,Company has responded to the consumer and the ...,Closed with explanation,Yes,South,South Atlantic,2022-08-06,COMP-0121,10

In [ ]:
df = df.fillna({
    'Sub-product' : 'Not Specified' ,
    'Sub-issue' : 'Not Specified' ,
    'Company public response' : 'Not Specified' ,
    'Timely response?' : 'Not Specified'
})

In [ ]:
df.head(1)

,Complaint ID,Submitted via,Date submitted,Date received,State,State_Latitude,State_Longitude,Product,Sub-product,Issue,Sub-issue,Company public response,Company response to consumer,Timely response?,Census_Region,Census_Division,Company_Response_Date,Company_ID_1081,Response_Time_Days
0,4848023,Referral,2021-10-24,2021-10-27,NY,42.165726,-74.948051,Mortgage,Conventional home mortgage,Applying for a mortgage or refinancing an exis...,Not Specified,Company has responded to the consumer and the ...,Closed with explanation,Yes,Northeast,Middle Atlantic,2021-10-30,COMP-0820,6

In [ ]:
df.isnull().sum()

Complaint ID                    0
Submitted via                   0
Date submitted                  0
Date received                   0
State                           0
State_Latitude                  0
State_Longitude                 0
Product                         0
Sub-product                     0
Issue                           0
Sub-issue                       0
Company public response         0
Company response to consumer    0
Timely response?                0
Census_Region                   0
Census_Division                 0
Company_Response_Date           0
Company_ID_1081                 0
Response_Time_Days              0
dtype: int64

In [ ]:
df_company = pd.read_excel("data/Consumer Financial Complaints Dataset.xlsx", sheet_name='Company')

In [ ]:
df_company.shape

(1081, 9)

In [ ]:
df_company.head()

,Company_ID_1081,Market_Share_Percent,Reputation_Score,Enforcement_History,Company_Size_Tier,Complaint_Count,Timely_Response_Rate,Avg_Response_Time_Days,Complaints_per_1pct_Share
0,COMP-0001,0.0385,75,No,Small,50,0.900000,14.600000,1298.7013
1,COMP-0002,0.0781,82,No,Small,63,0.920635,13.285714,806.6581
2,COMP-0003,0.0169,63,No,Small,61,0.967213,13.278689,3609.4675
3,COMP-0004,0.0271,95,No,Small,56,0.946429,16.160714,2066.4207
4,COMP-0005,0.0273,69,No,Small,70,0.957143,15.228571,2564.1026

In [ ]:
df_merged = pd.merge(df, df_company, on='Company_ID_1081', how='left')

In [ ]:
df_merged.head(1)

,Complaint ID,Submitted via,Date submitted,Date received,State,State_Latitude,State_Longitude,Product,Sub-product,Issue,...,Company_ID_1081,Response_Time_Days,Market_Share_Percent,Reputation_Score,Enforcement_History,Company_Size_Tier,Complaint_Count,Timely_Response_Rate,Avg_Response_Time_Days,Complaints_per_1pct_Share
0,4848023,Referral,2021-10-24,2021-10-27,NY,42.165726,-74.948051,Mortgage,Conventional home mortgage,Applying for a mortgage or refinancing an exis...,...,COMP-0820,6,0.0099,92,No,Small,56,0.910714,12.875,5656.5657

In [ ]:
df_merged.shape

(62516, 27)

In [ ]:
df_merged.to_csv('cleaned_financial_complaints.csv', index=False)